### ISSUE TITLE
Newrelic >= 13.9.x breaks Next.js standalone + pnpm

### ISSUE THREAD

**Issue by dippas** [newrelic/node-newrelic#3917]
## Description

After upgrading `newrelic` from `13.8.0` to `13.19.2`, the agent fails to load at runtime in a Next.js standalone output with pnpm:

```
⨯ unhandledRejection: Error: An error occurred while loading instrumentation hook:
  Failed to load external module newrelic-6f673843702b4419:
  Error: Cannot find module '/app/node_modules/.pnpm/@apm-js-collab+code-transformer@0.12.0/node_modules/meriyah/dist/meriyah.mjs'
```

The Orchestrion-JS rewrite ([nodejs/orchestrion-js#41](https://github.com/nodejs/orchestrion-js/pull/41)) replaced the native SWC parser with `meriyah` (ESM-only). Next.js standalone file tracing  cannot follow pnpm's `.pnpm` symlink structure to include `meriyah` in the output.

## Expected Behavior

`newrelic` loads successfully at runtime in Next.js standalone output with pnpm, as it did in `13.8.0`.

## Troubleshooting or NR Diag results

Attempted workaround via `next.config.ts`:

```ts
serverExternalPackages: ['newrelic']
```

## Steps to Reproduce

1. Next.js app with `output: 'standalone'`
2. `instrumentation.ts` with `await import('newrelic')`
3. Build and deploy standalone output in Docker
4. Runtime error on startup

## Your Environment

- Node: 22 (alpine)
- Next.js: 16.2.4
- pnpm: 10.33.0
- newrelic: 13.19.2 (works on 13.8.0)
- Build: `next build --turbopack` with `output: 'standalone'`
- OS: Alpine Linux (Docker), deployed on Azure

## Additional context

Dependency chain: `newrelic` → `@apm-js-collab/tracing-hooks@^0.6.0` → `@apm-js-collab/code-transformer@^0.12.0` → `meriyah@^6.1.4`

In `13.8.0`, `code-transformer` was `^0.8.0` which had no `meriyah` dependency. Likely affects all users on Next.js standalone + pnpm with newrelic >= 13.9.x.

**Comment by Newrelic-Boomi** [comment]
https://new-relic.atlassian.net/browse/NR-555742

**Comment by bizob2828** [comment]
@dippas have you reached out the pnpm? I'm not sure how this is an issue with our agent. This seems more like Next.js or pnpm setup.

**Comment by dippas** [comment]
No I did not, and I understand this sits at the intersection of newrelic, pnpm, and Next.js standalone file tracing.

That said, this is a regression from our perspective given the only change was upgrading `newrelic` from `13.8.0` to `13.19.2`, the new transitive dependency on `meriyah`, which was introduced via `@apm-js-collab/code-transformer@^0.12.0` is not being included in the Next.js standalone output when using pnpm.

For now we've pinned to `13.8.0` as a workaround but wondering if is there a recommended configuration for Next.js standalone + pnpm users to use newer agent versions?

**Comment by jsumners-nr** [comment]
> the new transitive dependency on `meriyah`, which was introduced via `@apm-js-collab/code-transformer@^0.12.0` is not being included in the Next.js standalone output when using pnpm

This is where we are having difficulty understanding our responsibility. This statement makes it clear that this is a project management issue, not an issue with the agent.

We are unable to change out the dependency you are having difficulty with. This dependency is necessary for us to support the direction the JavaScript ecosystem is moving toward.

> For now we've pinned to `13.8.0` as a workaround but wondering if is there a recommended configuration for Next.js standalone + pnpm users to use newer agent versions?

We standardize on the de-facto standard package manager that ships with Node.js: npm. We are also not well versed in the intricacies of Next.js. We'd welcome your input as an expert with these alternate technologies on how to solve this issue.

**Comment by dippas** [comment]
Understood, thanks for clarifying the support scope.

**Comment by dippas** [comment]
If anyone finds this, I've managed to fix it by adding the following to `next.config.ts`

  ```ts
  outputFileTracingIncludes: {
    '/*': ['../../node_modules/.pnpm/meriyah@*/node_modules/meriyah/dist/meriyah.mjs'],
  },
  serverExternalPackages: ['newrelic'],
  ```

**Comment by jsumners-nr** [comment]
Happy to hear you have found a solution. Thank you for posting it for others to learn from.
