### ISSUE TITLE
Package version 6.4.1 crashes immediately

### ISSUE THREAD

**Issue by hempels** [newrelic/node-newrelic#330]
After upgrading to 6.4.1 via npm, our application crashes immediately when attempting to handle incoming requests:

```
TypeError: this.getHeaders is not a function
    at ServerResponse.wrappedWriteHead [as writeHead] (/.../node_modules/newrelic/lib/instrumentation/core/http.js:334:33)
    at ServerResponse.writeHead (/.../node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:574:10)
    at ServerResponse.wrappedResEnd [as end] (/.../node_modules/newrelic/lib/instrumentation/core/http.js:272:18)
    at Array.write (/.../node_modules/finalhandler/index.js:297:9)
    at listener (/.../node_modules/on-finished/index.js:169:15)
    at onFinish (/.../node_modules/on-finished/index.js:100:5)
    at callback (/.../node_modules/ee-first/index.js:55:10)
    at IncomingMessage.onevent (/.../node_modules/ee-first/index.js:93:5)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at IncomingMessage.wrapped [as emit] (/.../node_modules/newrelic/lib/transaction/tracer/index.js:188:22)    at endReadableNT (_stream_readable.js:974:12)
    at Shim.applySegment (/.../node_modules/newrelic/lib/shim/shim.js:1425:20)
    at wrapper (/.../node_modules/newrelic/lib/shim/shim.js:2087:17)
```

**Comment by michaelgoin** [comment]
@hempels I'm sorry to hear that. 

Can you share some details on your app? What version of Node are you on? What server framework?

Thank you,

Michael

**Comment by hempels** [comment]
@michaelgoin those are fair questions - I should have included environment details.

Node: 6.10.2
Express: 4.17.1
Server: Ubuntu 16.04.1 LTS

**Comment by michaelgoin** [comment]
@hempels thank you for the information!

Unfortunately, we dropped support for Node 6 with major version 6+ of the agent. The change we just shipped assumes Node `v8.0.0` or higher.

While we do have a check in the `engines` field of `package.json`, we actually realized just after this last release we had missed updating our manual check/warning with the last major version bump. Which probably part of why this got missed. (We'll remedy that check with the next release).

I'm glad (and maybe a bit surprised) things have been going well so far but we cannot guarantee any changes we ship going forward will not break applications on Node v6. Please note: we'll also be dropping support for Node 8 via a major version bump later this year.

For our release and support policy, please see: https://docs.newrelic.com/docs/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent#version. We are roughly aligning with Node's LTS policy.

Here's the Node 6 release notes for reference of what breaking changes may impact your app: https://docs.newrelic.com/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-600

Sorry for the inconvenience,

Michael

**Comment by michaelgoin** [comment]
Closing this out as it appeared to be a version mismatch issue.

Don't hesitate to reach out if there are other issues.
