### ISSUE TITLE
1.2.0 produces restify errors

### ISSUE THREAD

**Issue by bsander** [newrelic/node-newrelic#101]
Immediately after upgrading newrelic from 1.1.1 to 1.2.0 in our restify server, all requests fail with two different error messages:

This error is emitted through our HTML formatter upon a valid request:

```
error: [Formatter:HTML]   Object function ( w ) {
                if ( !w.document ) {
                    throw new Error( "jQuery requires a window with a document" );
                }
                return factory( w );
            } has no method 'param'
    at Server.<anonymous> (/Users/Sander/src/some-project/node_modules/restify/lib/index.js:87:26)
    at Server.EventEmitter.emit (events.js:106:17)
    at Domain.onError (/Users/Sander/src/some-project/node_modules/restify/lib/server.js:780:30)
    at Domain.EventEmitter.emit (events.js:95:17)
    at process._fatalException (node.js:249:27)
    at process._asyncFatalException [as _fatalException] (/Users/Sander/src/some-project/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:199:34)
```

And worse, this uncaught exception is produced when a non-existant route is requested:

```
error: [Formatter:HTML]   /favicon.ico does not exist

/Users/Sander/src/some-project/node_modules/newrelic/node_modules/continuation-local-storage/context.js:66
      throw exception;
            ^
TypeError: Property 'undefined' of object  is not a function
    at ServerResponse.formatter (/Users/Sander/src/some-project/lib/formatter/htmlformatter.js:40:37)
    at ServerResponse.format (/Users/Sander/src/some-project/node_modules/restify/lib/response.js:104:27)
    at ServerResponse.send (/Users/Sander/src/some-project/node_modules/restify/lib/response.js:207:32)
    at emitRouteError (/Users/Sander/src/some-project/node_modules/restify/lib/server.js:151:21)
    at onRoute (/Users/Sander/src/some-project/node_modules/restify/lib/server.js:623:33)
    at wrapped (/Users/Sander/src/some-project/node_modules/newrelic/lib/instrumentation/restify.js:63:16)
    at Router.find (/Users/Sander/src/some-project/node_modules/restify/lib/router.js:473:9)
    at Router.wrappedFind [as find] (/Users/Sander/src/some-project/node_modules/newrelic/lib/instrumentation/restify.js:66:19)
    at Server._route (/Users/Sander/src/some-project/node_modules/restify/lib/server.js:617:21)
    at routeAndRun (/Users/Sander/src/some-project/node_modules/restify/lib/server.js:576:22)
```

I'm not sure what information I should provide about our application, maybe the stacktraces alone are enough for you guys. If not, please ask!
