### ISSUE TITLE
TypeError: self.agent.tracer.bindFunction(...).apply is not a function

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#3468]
## Description
A customer reported that after upgrading to 13.6.0 they were seeing crashes around express.  I can't reproduce but it's clear we are sometimes attempting to wrap a middleware function that is not actually a function.

## Expected Behavior
Return original handle when it is not a function

## Steps to Reproduce
Agent crash:

```
TypeError: self.agent.tracer.bindFunction(...).apply is not a function
… wrappedHandler (/nri-nodejs--authn/node_modules/newrelic/lib/subscribers/middleware-wrapper.js:98:78)
                                       at newFn (/app/node_modules/express-async-errors/index.js:16:20)
              at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
                                          at next (/app/node_modules/express/lib/router/route.js:149:13)
                                                   at <REDCATED> (/app/src/middlewares/<REDACTED>.js:43:3)
                         at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

```

## Additional context
I tried various permutations but I cannot figure this out.  However, I do realize that when we ported over the subscription based instrumentation there is a check in `shim.record` if the function we're trying to record is not a function just return the original.

the customer is using `express-validator`, I expect that is messing with the `handler` on a router at times

**Comment by Newrelic-Boomi** [comment]
https://new-relic.atlassian.net/browse/NR-482384

**Comment by jlowcs** [comment]
@bizob2828 in case that helps, from what I could gather from our issues in production (yikes), the issue was constrained to express routes defined using arrays, like this:
```js
app.get('/my-path', [myMiddleware]);
```

**Comment by bizob2828** [comment]
@jlowcs good to know. it appears we don't have a test for that scenario and may not be handling recording those middleware functions, I logged this [bug](https://github.com/newrelic/node-newrelic/issues/3472). We will prob issue another patch tomorrow, sorry for the troubles

**Comment by bizob2828** [comment]
@jlowcs please upgrade to [13.6.2](https://github.com/newrelic/node-newrelic/releases/tag/v13.6.2) for the use case you mentioned
