### ISSUE TITLE
`openai.chat.completions.parse` is not working with latest newrelic version `13.3.2`

### ISSUE THREAD

**Issue by Jean-CharlesTerrillon** [newrelic/node-newrelic#3379]
Hello there,
I need your help on new bug spotted this week after newrelic dependency upgrade.

After upgrading from `"newrelic": "13.2.1"` to `"newrelic": "13.3.2"`, OpenAI SDK is broken well calling `openai.chat.completions.parse(input);`

Error message & stack related to OpenAI SDK
```
TypeError: this._client.chat.completions.create(...)._thenUnwrap is not a function
    at Completions.parse
``` 

`openai.chat.completions.create(input)` still working

## Description

With OpenAI versions 5.21.0 or 5.19.1 => both works with NewRelic 13.2.1 version
It works also with 13.3.2 when NewRelic is **disabled** (in dev environment for example)

## Expected Behavior

No matter when calling this function

[NOTE]: NR Log : https://onenr.io/0qQa7P0a6R1

## Steps to Reproduce

Upgrade `newrelic` dependency to reproduce

**Comment by Newrelic-Boomi** [comment]
https://new-relic.atlassian.net/browse/NR-464946

**Comment by svetlanabrennan** [comment]
@Jean-CharlesTerrillon Thanks for the report. We'll look into this.

**Comment by bizob2828** [comment]
I can reproduce this.  It appears this is a bug in Node.js with using [tracingChannel.tracePromise](https://nodejs.org/docs/latest/api/diagnostics_channel.html#tracingchanneltracepromisefn-context-thisarg-args).

**Comment by jsumners-nr** [comment]
@Jean-CharlesTerrillon we released 13.3.3 yesterday that should address this.

**Comment by Jean-CharlesTerrillon** [comment]
> [@Jean-CharlesTerrillon](https://github.com/Jean-CharlesTerrillon) we released 13.3.3 yesterday that should address this.

Thank you very much for quick response and release ! 🚀 @jsumners-nr & @bizob2828
