### ISSUE TITLE
Slim Node.js Lambda layer/image fails with "Cannot find module '@opentelemetry/core'" since v14.3.2

### ISSUE THREAD

**Issue by im-hojung-lee** [newrelic/node-newrelic#4162]
## Description

Since `newrelic` v14.3.2, the agent crashes at startup with
`Error: Cannot find module '@opentelemetry/core'` on the **slim**
Node.js Lambda layer / container image, which ships without any
`@opentelemetry/*` packages.

Cause: #4151 added an unconditional `require('@opentelemetry/core')`
in the require chain `tracer/index.js → ... → lib/spans/timed-event.js →
lib/otel/normalize-timestamp.js`, which now runs on every agent startup —
not just when the OTel bridge is used. The slim build strips
`@opentelemetry/*`, so it now crashes unconditionally.

## Expected Behavior

Slim layer/image should start without requiring any `@opentelemetry/*`
package when the OTel bridge isn't in use.

## Steps to Reproduce

1. Use `newrelic-lambda-layers-nodejs-slim` (or the slim layer) built
   against `newrelic@14.3.2`+.
2. Invoke the Lambda function.
3. `Error: Cannot find module '@opentelemetry/core'` at init.

Or: install `newrelic@14.3.2`, delete `node_modules/newrelic/node_modules/@opentelemetry`, then `require('newrelic')`.

## Your Environment

* Node: 22.x (Lambda `nodejs22.x`)
* `newrelic`: 14.3.2 (last known-good slim build: 14.3.1)
* Slim Lambda layer / `newrelic-lambda-layers-nodejs-slim` image

## Additional context

Slim build strips OTel here: https://github.com/newrelic/newrelic-lambda-layers/blob/master/nodejs/publish-layers.sh
Regression introduced by #4151.

**Comment by Newrelic-Boomi** [comment]
https://new-relic.atlassian.net/browse/NR-596587

**Comment by jsumners-nr** [comment]
Please give release https://github.com/newrelic/node-newrelic/releases/tag/v14.3.3 a try.

+ `arn:aws:lambda:us-east-1:451483290750:layer:NewRelicNodeJS-slim:23`
+ `arn:aws:lambda:us-east-1:451483290750:layer:NewRelicNodeJSARM64-slim:23`
